AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  DeployId:
    Type: String
    Default: afsf34sfdg
  SourceCodeBucket:
    Type: String
    Default: afsf34sfdg
Resources:
  AnalyticsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: apiName
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: apiName
          KeyType: HASH
      TableName: EducativeAPIAnalytics
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EducativeRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
                - states.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: logs:*
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: "*"
              - Effect: Allow
                Action: dynamodb:UpdateItem
                Resource: !GetAtt AnalyticsTable.Arn
              - Effect: Allow
                Action:
                  - states:StartExecution
                  - states:StartSyncExecution
                Resource: !Sub "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:EducativeExpressFlow"
  API:
    Type: AWS::ApiGateway::RestApi
    Properties:
      BodyS3Location:
        Bucket:
          Ref: SourceCodeBucket
        Key: !Sub "ApiGatewayOpenApiSpec.yaml"
      Description: Entry point for all the Serverless Microservices of the system
      Name: EducativeRestAPI
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: String
      RestApiId: !Ref API
      StageName: v1
  StepFunction:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionS3Location:
        Bucket:
          Ref: SourceCodeBucket
        Key: !Sub "StepFunction.json"
      DefinitionSubstitutions:
        AWS_ACCOUNT_ID: !Sub ${AWS::AccountId}
        AWS_REGION_ID: !Sub ${AWS::Region}
      RoleArn: !GetAtt ExecutionRole.Arn
      StateMachineName: EducativeExpressFlow
      StateMachineType: EXPRESS
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt ExecutionRole.Arn
      FunctionName: EducativeEcho
      Code:
        S3Bucket:
          Ref: SourceCodeBucket
        S3Key: !Sub "EducativeEcho.${DeployId}.zip"
      Runtime: nodejs16.x
      Timeout: 3
      MemorySize: 128
